### ISSUE TITLE
README needs examples - pretty please

### ISSUE THREAD

**Issue by jmeridth** [gholt/swiftly#68]
I am more than willing to issue a PR to do this, but since you wrote it, how about you get it started?  Please update your README with basic examples.  kthxbye.  <3 <3 <3

**Comment by jmeridth** [comment]
I see you have a sphinx link there, but some of your examples don't work. :cry:

**Comment by gholt** [comment]
Yes, the docs are where examples go. That and the cli help output which gets included in the docs. It certainly could be that some things are out of date. I'm not sure what though since I haven't been using this or Swift for quite some time. I try to maintain this based on feedback and PRs I get. Do you have any specific information as to what was broken?

**Comment by jmeridth** [comment]
Nothing broken.  Seem we disagree on "docs are where examples go".  The easiest example of getting connected and basic usage should be in the README IMO.  I can get a PR done and added there.  At least it will speak more to my intent. :smile:

**Comment by kerwin59** [comment]
Install info and examples I use. Hope it's useful:
https://github.com/kerwin59/swiftly/blob/master/swiftly.md
